---
version: 2
jobs:
   build-xenial:
     docker:
       - image: circleci/buildpack-deps:xenial-scm
     environment:
       - OCPN_TARGET:  xenial
     steps:
       - checkout
       - run: >
           echo "deb-src http://us.archive.ubuntu.com/ubuntu/ xenial main"
           | sudo tee -a /etc/apt/sources.list
       - run: >
           echo "deb-src http://us.archive.ubuntu.com/ubuntu/ xenial-updates main"
           | sudo tee -a /etc/apt/sources.list
       - run: cat /etc/apt/sources.list
       - run: ci/circleci-build-debian.sh
       - run: ci/circleci-upload.sh
   build-bionic:
     docker:
       - image: circleci/buildpack-deps:bionic-scm
     environment:
       - OCPN_TARGET:  bionic
     steps:
       - checkout
       - run: >
           echo "deb-src http://us.archive.ubuntu.com/ubuntu/ bionic main"
           | sudo tee -a /etc/apt/sources.list
       - run: >
           echo "deb-src http://us.archive.ubuntu.com/ubuntu/ bionic-updates main"
           | sudo tee -a /etc/apt/sources.list
       - run: cat /etc/apt/sources.list
       - run: ci/circleci-build-debian.sh
       - run: ci/circleci-upload.sh
   build-buster:
     docker:
       - image: circleci/buildpack-deps:buster-scm
     environment:
       - OCPN_TARGET:  buster
     steps:
       - checkout
       - run: ci/circleci-build-debian.sh
       - run: ci/circleci-upload.sh
   build-flatpak:
     machine:
       image: circleci/classic:201808-01
     environment:
       - OCPN_TARGET:  flatpak
     steps:
       - checkout
       - run: ci/circleci-build-flatpak.sh
       - run: ci/circleci-upload.sh
   build-fedora:
     docker:
         - image: fedora:29
     environment:
       - OCPN_TARGET:  fedora
     steps:
       - run: su -c "dnf install -q -y git openssh-clients openssh-server"
       - checkout
       - run: ci/circleci-build-fedora.sh
       - run: ci/circleci-upload.sh
   build-mingw:
     docker:
         - image: fedora:29
     environment:
       - OCPN_TARGET:  mingw
     steps:
       - run: su -c "dnf install -q -y git openssh-clients openssh-server"
       - checkout
       - run: ci/circleci-build-mingw.sh
       - run: ci/circleci-upload.sh
   build-macos:
     macos:
       xcode: "10.0.0"
     environment:
       - OCPN_TARGET:  macos
     steps:
       - checkout
       - run: ci/circleci-build-macos.sh
       - run: ci/circleci-upload.sh
   build-armhf-buster:
     environment:
       - OCPN_TARGET:  build-armhf-buster
       - CLOUDSMITH_PKG_EXT: exe
     steps:
       - checkout
       - setup_remote_docker:
       - run:
     command: |
     docker run --rm --privileged multiarch/qemu-user-static:register
     docker run opencpn/raspbian-buster:plugin_build_tooling
     docker run: bash ci/circleci-build-debian.sh
       #- run: bash ci/circleci-upload.sh
workflows:
  version: 2
  build_all:
    jobs:
      - build-xenial:
          filters:
            branches:
              only: ci
      - build-bionic:
          filters:
            branches:
              only: ci
      - build-buster:
          filters:
            branches:
              only: ci
      - build-flatpak:
          filters:
            branches:
              only: ci
      - build-fedora:
          filters:
            branches:
              only: ci
      - build-macos:
          filters:
            branches:
              only: ci
      - build-mingw:
          filters:
            branches:
              only: ci
      - build-armhf-buster:
          filters:
            branches:
              only: ci
